package com.securebank.fraud.insights;

import com.securebank.fraud.ai.AiOrchestrator;
import com.securebank.fraud.support.SupportedLocale;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

/**
 * Builds the spending insights: a category breakdown (deterministic facts) plus a
 * natural-language, localized summary generated by the {@link AiOrchestrator} (LLM when
 * live, deterministic template otherwise).
 *
 * <p>The breakdown is computed from the in-memory {@link DemoDataStore}; see that class for
 * the production note about querying the ledger read-model instead.</p>
 */
@Slf4j
@Service
public class InsightsService {

    private final DemoDataStore demoData;
    private final AiOrchestrator ai;

    public InsightsService(DemoDataStore demoData, AiOrchestrator ai) {
        this.demoData = demoData;
        this.ai = ai;
    }

    public InsightsResult insights(String customerId, SupportedLocale locale) {
        Map<String, BigDecimal> spend = demoData.spendByCategory(customerId);

        // Sort categories by amount descending for a stable, useful presentation.
        List<CategoryTotal> breakdown = spend.entrySet().stream()
                .map(e -> new CategoryTotal(e.getKey(), e.getValue()))
                .sorted(Comparator.comparing(CategoryTotal::getTotal).reversed())
                .toList();

        BigDecimal total = spend.values().stream()
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Build a compact, deterministic description of the facts for the AI to summarise.
        String description = buildDescription(breakdown, total);
        AiOrchestrator.Result summary = ai.summarize(description, locale);

        log.info("Insights for customer={} categories={} total={} fromLlm={}",
                customerId, breakdown.size(), total, summary.isFromLlm());

        return new InsightsResult(breakdown, summary.getText());
    }

    /** A neutral, language-agnostic-ish fact string the summariser frames into prose. */
    private String buildDescription(List<CategoryTotal> breakdown, BigDecimal total) {
        StringBuilder sb = new StringBuilder();
        sb.append("total ").append(total.setScale(2, RoundingMode.HALF_EVEN)).append("; ");
        for (CategoryTotal ct : breakdown) {
            BigDecimal pct = total.signum() == 0 ? BigDecimal.ZERO
                    : ct.getTotal().multiply(BigDecimal.valueOf(100))
                        .divide(total, 0, RoundingMode.HALF_EVEN);
            sb.append(ct.getCategory()).append(' ')
              .append(ct.getTotal().setScale(2, RoundingMode.HALF_EVEN))
              .append(" (").append(pct).append("%); ");
        }
        return sb.toString().trim();
    }

    /** One category and its total spend. */
    @Value
    public static class CategoryTotal {
        String category;
        BigDecimal total;
    }

    /** The full insights result: breakdown + localized summary. */
    @Value
    public static class InsightsResult {
        List<CategoryTotal> breakdown;
        String summary;
    }
}
